nelmio_api_doc:
    documentation:
        info:
            title: Balancer
            description: API for balancing processes
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
