version: '3.9'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: balancer
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

